on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: distributionregistry.azurecr.io
        username: ${{ secrets.acr_distributionregistry_username }}
        password: ${{ secrets.acr_distributionregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t distributionregistry.azurecr.io/aksdisttest:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push distributionregistry.azurecr.io/aksdisttest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdisttest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azure-vote-test | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azure-vote-test`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azure-vote-test
        container-registry-url: distributionregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_distributionregistry_username }}
        container-registry-password: ${{ secrets.acr_distributionregistry_password }}
        secret-name: aksdisttestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azure-vote-test
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          distributionregistry.azurecr.io/aksdisttest:${{ github.sha }}
        imagepullsecrets: |
          aksdisttestdockerauth
